blog/urls.py
from django.conf.urls import url

urlpatterns = [
    url(r'^$', BlogListView.as_view(), name="blog_index"),
    url(r'^(?P<pk>\d+)/detail/$', BlogDetailView.as_view(), name="blog_detail"),
    url(r'^(?P<pk>\d+)/add/$', BlogCreate.as_view(), name="blog_add"),
    url(r'^(?P<pk>\d+)/edit/$', BlogUpdate.as_view(), name="blog_edit"),
    url(r'^(?P<pk>\d+)/delete/$', BlogDelete.as_view(), name="blog_delete"),
]

broomtrade/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/', "django.contrib.auth.views.login", name="login"),
    url(r'^logout/', "django.contrib.auth.views.logout", name="logout"),
    url(r'^blog/', include('blog.urls')),
    url(r'^categories/', include('categories.urls')),
    url(r'^goods/', include('goods.urls')),
    url(r'^guestbook/', include('guestbook.urls')),
    url(r'^imagepool/', include('imagepool.urls')),
    url(r'^news/', include('news.urls')),
    url(r'^$', include('main.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

goods/urls.py
from django.conf.urls import url
from goods.views import GoodsListView, GoodDetailView, GoodCreate, GoodUpdate, GoodDelete

urlpatterns = [
    url(r'^(?P<pk>\d+)/$', GoodsListView.as_view(), name="goods_index"),
    url(r'^(?P<pk>\d+)/detail/$', GoodDetailView.as_view(), name="goods_detail"),
    url(r'^(?P<pk>\d+)/add/$', GoodCreate.as_view(), name="goods_add"),
    url(r'^(?P<pk>\d+)/edit/$', GoodUpdate.as_view(), name="goods_edit"),
    url(r'^(?P<pk>\d+)/delete/$', GoodDelete.as_view(), name="goods_delete"),
]

goods/models.py
from django.db import models
from categories.models import Category
from django.core.urlresolvers import reverse

# Create your models here.
class Good(models.Model):
    name = models.CharField(max_length=50, unique=True, db_index=True, verbose_name="Название")
    category = models.ForeignKey(Category, verbose_name="Категория")
    description = models.TextField(verbose_name="Краткое описание")
    content = models.TextField(verbose_name="Полное описание")
    price = models.FloatField(db_index=True, verbose_name="Цена, руб.")
    price_acc = models.FloatField(null=True, blank=True, verbose_name="Цена с учетом скидки, руб.")
    in_stock = models.BooleanField(default=True, db_index=True, verbose_name="Есть в наличии")
    featured = models.BooleanField(default=False, db_index=True, verbose_name="Рекомендуемый")
    image = models.ImageField(upload_to="goods/list", verbose_name="Основное изображение")

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        try:
            this_record = Good.objects.get(pk=self.pk)
            if this_record.image != self.image:
                this_record.image.delete(save=False)
        except:
            pass
        super(Good, self).save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        self.image.delete(save=False)
        super(Good, self).delete(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("goods_detail", kwargs={"pk": self.pk})

    class Meta:
        verbose_name = "товар"
        verbose_name_plural = "товары"


class GoodImage(models.Model):
    good = models.ForeignKey(Good)
    image = models.ImageField(upload_to="goods/detail", verbose_name="Дополнительное изображение")

    def save(self, *args, **kwargs):
        try:
            this_record = GoodImage.objects.get(pk=self.pk)
            if this_record.image != self.image:
                this_record.image.delete(save=False)
        except:
            pass
        super(GoodImage, self).save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        self.image.delete(save=False)
        super(GoodImage, self).delete(*args, **kwargs)

    class Meta:
        verbose_name = "изображение к товару"
        verbose_name_plural = "изображения к товару"

goods/forms.py
from goods.models import Good
from django import forms

class GoodForm(forms.ModelForm):
    class Meta:
        model = Good
        fields = "__all__"

goods/views.py
from django.contrib import messages
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.views.generic.base import ContextMixin, TemplateView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import DeleteView
from generic.mixins import CategoryListMixin, PageNumberMixin
from goods.models import Good
from categories.models import Category
from goods.models import GoodImage
from goods.forms import GoodForm
from django.forms.models import inlineformset_factory
from generic.controllers import PageNumberView
from django.shortcuts import redirect
from django.core.urlresolvers import reverse

# Create your views here.
class SortMixin(ContextMixin):
    sort = "0" #Sorting by Good's name, default sorting (сортировка по имени)
    order = "A" #Sort Ascending (сортировка по возрастанию)

    def get_context_data(self, **kwargs):
        context = super(SortMixin, self).get_context_data(**kwargs)
        context["sort"] = self.sort
        context["order"] = self.order
        return context


class GoodsListView(PageNumberView, ListView, SortMixin, CategoryListMixin):
    model = Good
    template_name = "goods_index.html"
    paginate_by = 10
    cat = None

    def get(self, request, *args, **kwargs):
        if self.kwargs["pk"] is None:
            self.cat = Category.objects.first()
        else:
            self.cat = Category.objects.get(pk=self.kwargs["pk"])
        return super(GoodsListView, self).get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(GoodsListView, self).get_context_data(**kwargs)
        context["category"] = self.cat
        return context

    def get_queryset(self):
        goods = Good.objects.filter(category=self.cat)
        if self.sort == "2":
            if self.order == "D":
                goods = goods.order_by("-in_stock", "name")
            else:
                goods = goods.order_by("in_stock", "name")
        elif self.sort == "1": #sorting by price and name
            if self.order == "D": #Descending sorting (сортировка по убыванию)
                goods = goods.order_by("-price", "name")
            else:
                goods = goods.order_by("price", "name")
        else:
            if self.order == "D":
                goods = goods.order_by("-name")
            else:
                goods = goods.order_by("name")
        return goods

class GoodDetailView(PageNumberView, DetailView, SortMixin, PageNumberMixin):
    model = Good
    template_name = "good.html"


GoodImagesFormset = inlineformset_factory(Good, GoodImage, fields="__all__", can_order=True)

class GoodCreate(PermissionRequiredMixin, PageNumberView, TemplateView, SortMixin, PageNumberMixin):
    permission_required = 'goods.add_good'
    template_name = "good_add.html"
    cat = None
    form = None
    formset = None

    def get(self, request, *args, **kwargs):
        if self.kwargs["pk"] is None:
            self.cat = Category.objects.first()
        else:
            self.cat = Category.objects.get(pk=self.kwargs["pk"])
        self.form = GoodForm(initial={"category":self.cat})
        self.formset = GoodImagesFormset()
        return super(GoodCreate, self).get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(GoodCreate, self).get_context_data(**kwargs)
        context["category"] = self.cat
        context["form"] = self.form
        context["formset"] = self.formset
        return context

    def post(self, request, *args, **kwargs):
        self.form = GoodForm(request.POST, request.FILES)
        if self.form.is_valid():
            new_good = self.form.save()
            self.formset = GoodImagesFormset(request.POST, request.FILES, instance=new_good)
            if self.formset.is_valid():
                self.formset.save()
                messages.add_message(request, messages.SUCCESS, "Товар успешно добавлен")
                return redirect(reverse("goods_index", kwargs={"pk": new_good.category.pk}) + \
                                "?page=" + self.request.GET["page"] + "&sort=" + self.request.GET["sort"] + \
                                "&order=" + self.request.GET["order"])
        if self.kwargs["pk"] is None:
            self.cat = Category.objects.first()
        else:
            self.cat = Category.objects.get(pk=self.kwargs["pk"])
        self.formset = GoodImagesFormset(request.POST, request.FILES)
        return super(GoodCreate, self).get(request, *args, **kwargs)


class GoodUpdate(PermissionRequiredMixin, PageNumberView, TemplateView, SortMixin, PageNumberMixin):
    permission_required = 'goods.change_good'
    good = None
    template_name = "good_edit.html"
    form = None
    formset = None

    def get(self, request, *args, **kwargs):
        self.good = Good.objects.get(pk=self.kwargs["pk"])
        self.form = GoodForm(instance=self.good)
        self.formset = GoodImagesFormset(instance=self.good)
        return super(GoodUpdate, self).get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(GoodUpdate, self).get_context_data(**kwargs)
        context["good"] = self.good
        context["form"] = self.form
        context["formset"] = self.formset
        return context

    def post(self, request, *args, **kwargs):
        self.good = Good.objects.get(pk=self.kwargs["pk"])
        self.form = GoodForm(request.POST, request.FILES, instance=self.good)
        self.formset = GoodImagesFormset(request.POST, request.FILES, instance=self.good)
        if self.form.is_valid():
            self.form.save()
            if self.formset.is_valid():
                self.formset.save()
                messages.add_message(request, messages.SUCCESS, "Товар успешно изменен")
                return redirect(reverse("goods_index", kwargs={"pk":self.good.category.pk}) + \
                                "?page=" + self.request.GET["page"] + "&sort=" + self.request.GET["sort"] + \
                                "&order=" + self.request.GET["order"])
        return super(GoodUpdate, self).get(request, *args, **kwargs)


class GoodDelete(PermissionRequiredMixin, PageNumberView, DeleteView, SortMixin, PageNumberMixin):
    permission_required = 'goods.delete_good'
    model = Good
    template_name = "good_delete.html"

    def post(self, request, *args, **kwargs):
        self.success_url = reverse("goods_index", kwargs={"pk":Good.objects.get(pk=kwargs["pk"]).category.pk}) + \
                                    "?page=" + self.request.GET["page"] + "&sort=" + self.request.GET["sort"] + \
                                    "&order=" + self.request.GET["order"]
        messages.add_message(request, messages.SUCCESS, "Товар успешно удален")
        return super(GoodDelete, self).post(request, *args, **kwargs)

goods/templates/good.html
{% extends "main.html" %}
{% load bbcode_tags %}
{% block title %}{{ object.name }} :: {{ oject.category.name }}{% endblock %}
{% block main %}
    <h2>{{ object.name }}</h2>
    <p>Категория: {{ object.category.name }}</p>
    <div class="good-images">
        <div><img src="{{ object.image.url }}" alt=""></div>
        {% for goodimage in object.goodimage_set.all %}
            <div><img src="{{ goodimage.image.url }}" alt=""></div>
        {% endfor %}
    </div>
    <div>{{ object.content|bbcode|safe }}</div>
    <p>Цена, руб.:{% if object.price_acc > 0 %}<span class="old-price">
        {{ object.price }}</span>&nbsp;&nbsp;{{ object.price_acc }}{% else %}
        {{ object.price }}{% endif %}
    </p>
    {% if object.in_stock %}
        <p>Нет в наличии.</p>
    {% endif %}
    <p><a href="{% url "goods_index"  pk=object.category.pk %}
        ?page={{ pn }}&sort={{ sort }}&order={{ order }}">Назад</a>
    </p>
    <p>&nbsp;</p>
{% endblock %}

goods/templates/good_add.html
{% extends "main.html" %}
{% block title %}Добавление товара:: {{ category.name }}{% endblock %}
{% block main %}
    <h2>Добавление товара</h2>
    <div class="form">
        <form action="" method="post" enctype="multipart/form-data">
            {% include "generic/form.html" %}
            {% include "generic/formset.html" %}
            <div class="submit-button"><input type="submit" value="Добавить"></div>
        </form>
    </div>
    <p><a href="{% url "goods_index" pk=category.pk %}?page={{ pn }}&sort={{ sort }}&order={{ order }}">Назад</a></p>
{% endblock %}

goods/templates/good_delete.html
{% extends "main.html" %}
{% load bbcode_tags %}
{% block title %}Удаление товара :: {{ object.name }}{% endblock %}
{% block main %}
    <h2>Удаление товара</h2>
    <h4>{{ object.name }}</h4>
    <p>Категория :: {{ object.category.name }}</p>
    <div>{{ object.content|bbcode|safe }}</div>
    <p>Цена, руб.:{% if object.price_acc > 0 %}<span class="old-price">
        {{ object.price }}</span>&nbsp;&nbsp;{{ object.price_acc }}{% else %}
        {{ object.price }}{% endif %}
    </p>
    {% if object.in_stock %}
        <p>Нет в наличии.</p>
    {% endif %}
    {% if object.featured %}
        <p>Рекомендуемый.</p>
    {% endif %}
    <form action="" method="post">
        {% csrf_token %}
        <input type="submit" value="Удалить">
    </form>
    <p><a href="{% url "goods_index"  pk=object.category.pk %}
        ?page={{ pn }}&sort={{ sort }}&order={{ order }}">Назад</a>
    </p>
{% endblock %}

goods/templates/good_edit.html
{% extends "main.html" %}
{% block title %}Правка товара :: {{ good.name }}{% endblock %}
{% block main %}
    <h2>Правка товара</h2>
    <div class="form">
        <form action="" method="post" enctype="multipart/form-data">
            {% include "generic/form.html" %}
            {% include "generic/formset.html" %}
            <div class="submit-button"><input type="submit" value="Изменить"></div>
        </form>
    </div>
    <p><a href="{% url "goods_index" pk=good.category.pk %}?page={{ pn }}&sort={{ sort }}&order={{ order }}>Назад</a></p>
{% endblock %}

goods/templates/goods_index.html
{% extends "main.html" %}
{% load thumbnail %}
{% block title %}{{ category.name }}{% endblock %}
{% block main %}
    {% include "generic/messages.html" %}
    <h2>{{ category.name }}</h2>
    {% if perms.goods.add_good %}
        <p><a href="{% url "goods_add" pk=category.pk %}?page={{ page_obj.number }}&sort={{ sort }}&order={{ order }}">Добавить товар</a></p>
    {% endif %}
    <table class="list-table">
        <tr>
            <th>Миниатюра</th>
            <th><a href="?sort=0&order={% if sort == "0" and order == "A" %}D{% else %}A{% endif %}">{% if sort == "0" %}{% if order == "D" %}&#9660;{% else %}&#9650;{% endif %}{% endif %}&nbsp;Название</a>
            </th>
            <th>Описание</th>
            <th><a href="?sort=1&order={% if sort == "1" and order == "A" %}D{% else %}A{% endif %}">{% if sort == "1" %}{% if order == "D" %}&#9660;{% else %}&#9650;{% endif %}{% endif %}&nbsp;Цена, руб.</a></th>
            <th><a href="?sort=2&order={% if sort == "2" and order == "A" %}D{% else %}A{% endif %}">{% if sort == "2" %}{% if order == "D" %}&#9660;{% else %}&#9650;{% endif %}{% endif %}&nbsp;Есть в наличии</a></th>
            {% if perms.goods.change_good %}
                <th>&nbsp;</th>
            {% endif %}
            {% if perms.goods.delete_good %}
                <th>&nbsp;</th>
            {% endif %}
        </tr>
        {% for object in object_list %}
            <tr>
                <td class="centered"><a href="{% url "goods_detail" pk=object.pk %}?page={{ page_obj.number }}&sort={{ sort }}&order={{ order }}"><img alt="image" src="{% thumbnail object.image "base" %}"></a>
                </td>
                <td><a href="{% url "goods_detail" pk=object.pk %}?page={{ page_obj.number }}&sort={{ sort }}&order={{ order }}">{{ object.name }}</a></td>
                <td>{{ object.description }}</td>
                <td class="centered">
                    {% if object.price_acc > 0 %}
                        <span class="old-price">{{ object.price }}</span>
                        <br>
                        {{ object.price_acc }}
                    {% else %}
                        {{ object.price }}
                    {% endif %}
                </td>
                <td class="centered">{% if object.in_stock %}+{% endif %}</td>
                {% if perms.page.change_good %}
                    <td class="centered"><a href="{% url "goods_edit" pk=object.pk %}?page={{ page_obj.number }}&sort={{ sort }}&order={{ order }}">Изменить</a></td>
                {% endif %}
                {% if perms.page.delete_good %}
                    <td class="centered"><a href="{% url "goods_delete" pk=object.pk %}?page={{ page_obj.number }}&sort={{ sort }}&order={{ order }}">Удалить</a></td>
                {% endif %}
            </tr>
        {% endfor %}
    </table>
    {% include "generic/pagination.html" %}
{% endblock %}